# define ALWAYS_SHOW_INITINFO 1
# define INITINFO_DURATION 5

/*
#define DETECT_NATIVE_FEATURES 0
#define CONSOLE_DEBUG_PRINT 1
*/
#define RS232_DEBUG_PRINT 1

#define CONF_WITH_DDB1 1
#define CONF_WITH_PICOGFX 1
#define CONF_WITH_3D_OBJECTS 0
